name: demo
on: [push]
jobs: 
  show_python_version: 
    steps:
     - name: Show-python-version
     - run: python -V
   ##- name: test-pylint
     ## runs-on: ubuntu-lates
      ##steps: 
       ##- run: py.test --pylint
  
