name: demo
on: [push]
jobs: 
  runs-on: ubuntu-latest 
  show-python-version:   
    steps:
      - run: python -V
  test-pylint:
    runs-on: ubuntu-lates
    steps: 
      - run: py.test --pylint
  
