name: demo
on: [push]
jobs: 
  show_python_version: 
    runs-on: ubuntu-latest
    steps:
     - name: Show-python-version
       run: python -V
     
  test_pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: pip_install_dependiences
        run: pip install -r requirements.txt
      - name: Install Pylint
        run: pip install pylint
      - name: Run Pylint
        run: pylint app.py
